# Generated by Django 6.0 on 2025-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('HOME', 'Home'), ('APARTMENT', 'Apartment'), ('BEACHFRONT', 'Beachfront'), ('MOUNTAIN', 'Mountain'), ('CABIN', 'Cabin'), ('VILLA', 'Villa'), ('OTHER', 'Other')], default='HOME', max_length=20),
        ),
    ]
